[package]
name = "rust"
version = "0.1.0"
authors = ["Thomas Hartmann <thomas.o.hartmann@gmail.com>"]

[dev-dependencies]
# speculate = "0.0.26"

[dependencies]
num = "0.2"
regex = "1"
lazy_static = "1.1.0"
